x-airflow-common: &airflow-common
  image: airflow_airbridge
  build:
    context: ../../
    dockerfile: ./docker/airflow/Dockerfile
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: "DUMMY"
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
    AIRFLOW__WEBSERVER__INSTANCE_NAME: ${AIRFLOW_WEBSERVER_INSTANCE_NAME}
    AIRFLOW__WEBSERVER__NAVBAR_COLOR: ${AIRFLOW_NAVBAR_COLOR}
    AIRFLOW_CONN_AIRBRIDGE_BROKER: ${AIRBRIDGE_BROKER_URL}/?exchange_name=${AIRBRIDGE_EXCHANGE_NAME}
    AIRBRIDGE_INSTANCE_ID: ${AIRBRIDGE_INSTANCE_ID}
  volumes: !override
    - ../../${DAG_DIR}:/opt/airflow/dags
  networks:
    - default
    - rabbitmq

services:
  airflow-init:
    <<: *airflow-common

  airflow-webserver:
    <<: *airflow-common
    ports: !override
      - "${WEBSERVER_PORT}:8080"

  airflow-scheduler:
    <<: *airflow-common

  airflow-triggerer:
    <<: *airflow-common

  airflow-worker:
    <<: *airflow-common

  airflow-airbridge:
    image: airflow_airbridge
    build:
      context: ../../
      dockerfile: ./docker/airflow/Dockerfile
    entrypoint: airbridge
    command: |
      --instance-id ${AIRBRIDGE_INSTANCE_ID}
      --broker-url ${AIRBRIDGE_BROKER_URL}
      --exchange-name ${AIRBRIDGE_EXCHANGE_NAME}
      --airflow-url http://airflow:airflow@airflow-webserver:8080/
    restart: on-failure
    networks:
      - default
      - rabbitmq

networks:
  default:
  rabbitmq:
    name: rabbitmq
    external: true
