x-airflow-common:
  &airflow-common
  image: airflow_airbridge
  build:
    context: ../../
    dockerfile: ./docker/airflow/Dockerfile
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: "DUMMY"
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
    AIRFLOW__WEBSERVER__NAVBAR_COLOR: ${AIRFLOW_NAVBAR_COLOR}
    AIRBRIDGE__GENERAL__INSTANCE_ID: ${AIRBRIDGE__GENERAL__INSTANCE_ID}
    AIRBRIDGE__BROKER__HOST: ${AIRBRIDGE__BROKER__HOST}
    AIRBRIDGE__BROKER__LOGIN: ${AIRBRIDGE__BROKER__LOGIN}
    AIRBRIDGE__BROKER__PASSWORD: ${AIRBRIDGE__BROKER__PASSWORD}
    AIRBRIDGE__BROKER__EXCHANGE: ${AIRBRIDGE__BROKER__EXCHANGE}
    AIRBRIDGE__BROKER__QUEUE_PREFIX: ${AIRBRIDGE__BROKER__QUEUE_PREFIX}
  volumes: !override
    - ../../${DAG_DIR}:/opt/airflow/dags
  networks:
    - default
    - rabbitmq

services:
  airflow-init:
    <<: *airflow-common

  airflow-webserver:
    <<: *airflow-common
    ports: !override
      - "${WEBSERVER_PORT}:8080"

  airflow-scheduler:
    <<: *airflow-common

  airflow-triggerer:
    <<: *airflow-common

  airflow-worker:
    <<: *airflow-common

  airflow-airbridge:
    image: airflow_airbridge
    build:
      context: ../../
      dockerfile: ./docker/airflow/Dockerfile
    entrypoint: airbridge
    environment:
      AIRBRIDGE__GENERAL__INSTANCE_ID: ${AIRBRIDGE__GENERAL__INSTANCE_ID}
      AIRBRIDGE__BROKER__HOST: ${AIRBRIDGE__BROKER__HOST}
      AIRBRIDGE__BROKER__LOGIN: ${AIRBRIDGE__BROKER__LOGIN}
      AIRBRIDGE__BROKER__PASSWORD: ${AIRBRIDGE__BROKER__PASSWORD}
      AIRBRIDGE__BROKER__EXCHANGE: ${AIRBRIDGE__BROKER__EXCHANGE}
      AIRBRIDGE__BROKER__QUEUE_PREFIX: ${AIRBRIDGE__BROKER__QUEUE_PREFIX}
      AIRBRIDGE__AIRFLOW__HOST: airflow-webserver
      AIRBRIDGE__AIRFLOW__PORT: "8080"
      AIRBRIDGE__AIRFLOW__LOGIN: airflow
      AIRBRIDGE__AIRFLOW__PASSWORD: airflow
    restart: on-failure
    networks:
      - default
      - rabbitmq

networks:
  default:
  rabbitmq:
    name: rabbitmq
    external: true
